### ISSUE TITLE
Champion change for a few proposals.

### ISSUE THREAD

**Issue by koto** [tc39-transfer/.github#1]
I am taking over championing a few proposals after @mikesamuel. They are already in the tc39 repo, I'm in https://github.com/orgs/tc39/teams/delegates. I have write access to the last two repos. Can I get admin access to all three?

https://github.com/tc39/proposal-array-is-template-object
https://github.com/tc39/dynamic-import-host-adjustment
https://github.com/tc39/proposal-dynamic-code-brand-checks 

Mike, can you confirm it's not a hostile takeover? ;)

**Comment by littledan** [comment]
Should we discuss this in the https://github.com/tc39/Admin-and-Business/ repo?

**Comment by littledan** [comment]
cc @robpalme @bterlson @codehag @gesa @MylesBorins

**Comment by koto** [comment]
Happy to move this there, should I?

**Comment by mikesamuel** [comment]
> Mike, can you confirm it's not a hostile takeover? ;)

This is not a hostile takeover.

@koto is awesome, so this is definitely an upgrade for TC39.

**Comment by ljharb** [comment]
@koto issues can't be moved across orgs.

You'll probably need to file a new one there, and then we can close this one.

**Comment by koto** [comment]
Moved to https://github.com/tc39/Admin-and-Business/issues/97.
